export const ASSESSMENT_PHASES = {
  FILL_BLANK: "FILL_BLANK",

  PASSAGE_TRANSITION: "PASSAGE_TRANSITION",

  PASSAGE_READ: "PASSAGE_READ",

  PASSAGE_WRITE: "PASSAGE_WRITE",

  EMAIL_TRANSITION: "EMAIL_TRANSITION",

  COMPLETED: "COMPLETED",
};
